# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Brownie
tagline:          '깃 불로구'
description:      '너굴리'
url:              https://01045972746.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'jonghan.kim'
  url:            https://github.com/01045972746

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:             
  repo:             https://github.com/01045972746/01045972746.github.io

disqus:
  shortname:        brownie4597